### ISSUE TITLE
bug(v0.9.1): Cannot find module '../utils/teammate.js' — files missing from npm bundle

### ISSUE THREAD

**Issue by rodrigoeqnit** [Gitlawb/openclaude#1026]
## Description

After installing `@gitlawb/openclaude@0.9.1` via `npm install -g`, the CLI fails immediately on startup with:

```
ERROR  Cannot find module '../utils/teammate.js'
Require stack:
- C:\Users\...\node_modules\@gitlawb\openclaude\dist\cli.mjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1421:15)
    at getDefaultAppState (file:///.../@gitlawb/openclaude/dist/cli.mjs:235786:25)
    at t1 (file:///.../@gitlawb/openclaude/dist/cli.mjs:408149:44)
```

## Root Cause

`dist/cli.mjs` line 235786 does a dynamic `require()` at runtime:

```js
// src/state/AppStateStore.ts
import { createRequire as createRequire3 } from "node:module";
function getDefaultAppState() {
  const runtimeRequire = createRequire3(import.meta.url);
  const teammateUtils = runtimeRequire("../utils/teammate.js");
  ...
}
```

Because `import.meta.url` points to `dist/cli.mjs`, the path `../utils/teammate.js` resolves to **`<package-root>/utils/teammate.js`**. However, the published npm package does **not include** the `utils/` directory at the package root — only `dist/`, `src/`, `bin/`, and `node_modules/` are present.

## Affected versions

- `@gitlawb/openclaude@0.9.1` (latest as of 2026-05-05)
- Also confirmed on `@0.9.0`
- `@0.6.0` did **not** have this issue

## Environment

- Windows 11, Node v24.13.0, npm 11.x
- Also reproducible on Linux (confirmed by other users)

## Workaround

Manually create the two missing files (ESM syntax required — `package.json` has `"type": "module"`):

**`<package-root>/utils/teammateContext.js`**
```js
import { AsyncLocalStorage } from 'async_hooks';
const teammateContextStorage = new AsyncLocalStorage();
export function getTeammateContext() { return teammateContextStorage.getStore(); }
export function runWithTeammateContext(context, fn) { return teammateContextStorage.run(context, fn); }
export function isInProcessTeammate() { return teammateContextStorage.getStore() !== undefined; }
export function createTeammateContext(config) { return { ...config, isInProcess: true }; }
```

**`<package-root>/utils/teammate.js`**
```js
import { createTeammateContext, getTeammateContext, isInProcessTeammate, runWithTeammateContext } from './teammateContext.js';
// ... (isTeammate, isPlanModeRequired, etc.)
```

## Fix

The `utils/` directory (containing at minimum `teammate.js` and `teammateContext.js`) must be included in the npm bundle. Check the `files` field in `package.json` or the bundler config — `utils/` is likely being excluded unintentionally.

Alternatively, inline the teammate utilities directly into `cli.mjs` via the bundler instead of using a dynamic `require()`.

**Comment by guilhvic** [comment]
Tried the workarount but got the same results, hoping for a fix.

```
  ERROR  Cannot find module '../utils/teammate.js'
        Require stack:
        - C:\Users\gui\AppData\Roaming\npm\node_modules\@gitlawb\openclaude\dist\cli.mjs
```

<img width="671" height="129" alt="Image" src="https://github.com/user-attachments/assets/34d8cf89-3879-46f0-8094-794c14799a9e" />

**Comment by PawiX25** [comment]
Hey @rodrigoeqnit! I've investigated this issue and found the root cause. 

The crash was introduced in commit 1f66d32 (#1020), where `require` was changed to `createRequire(import.meta.url)`. While this likely resolved an ESM/CJS warning in testing, `createRequire` bypasses the Bun bundler entirely. As a result, `teammate.js` was no longer inlined into the NPM bundle (`dist/cli.mjs`), causing the CLI to fail at runtime since `utils/` is not included in the published package.

I've just submitted a PR (#1033) that replaces the dynamic require with a standard static `import`, which allows the bundler to properly inline the file again and fixes the crash.

In the meantime, if you need a working version locally, you can clone the repository, build it, and install it globally:
```bash
git clone https://github.com/Gitlawb/openclaude.git
cd openclaude
bun install
bun run build
npm install -g .
```
